### ISSUE TITLE
overflow of body

### ISSUE THREAD

**Issue by MostafaHamedAbdelmasoud** [creativecommons/cccatalog-dataviz#8]
## Problem Description

there is an attribute overflow auto which is default in css for body, which causes problem with UI

## Solution Description

adding in forced3.css file

``` css
body{
	overflow-x: hidden;
	overflow-y: scroll;
}
```

## Alternatives

we can make it without any scroll over X or Y axis.

``` css
body{
	overflow: hidden;
}
```

## Additional context

![scrollProblem](https://user-images.githubusercontent.com/36406025/75291104-6bb71580-57d6-11ea-98a7-9b96680babdf.PNG)

after adding these first lines:

![scrollSolve](https://user-images.githubusercontent.com/36406025/75291180-930de280-57d6-11ea-83dc-c77dcbb9868c.PNG)
